const countries = {
    "Id-ID": "Indonesian",
    "ar-SA": "Arabic",
    "de-DE": "German",
    "it-IT": "Italian",
    "es-ES": "Spanish",
    "ja-JP": "Japanese",
    "en-GB": "English",
    "fr-FR": "French",
    "ha-HA": "Hausa",
    "hi-HI": "Hindi",
    "ge-GE": "German",
    "gr-GR": "Greek",
    "gu-GU": "Gujarati",
  }